//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been deactivated.
        /// </summary>
        internal static string ACCOUNT_DEACTIVATED {
            get {
                return ResourceManager.GetString("ACCOUNT_DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account email is already existing in the application.
        /// </summary>
        internal static string ACCOUNT_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ACCOUNT_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user provided does not belong to quality control role.
        /// </summary>
        internal static string ACCOUNT_NOT_QUALITY_CONTROL {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_QUALITY_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account password cannot be changed.
        /// </summary>
        internal static string ACCOUNT_PASSWORD_RECOVERY_ERROR {
            get {
                return ResourceManager.GetString("ACCOUNT_PASSWORD_RECOVERY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screener category is mandatory for user profile with screener role.
        /// </summary>
        internal static string ACCOUNT_SCREENER_CATEGORY_MISSING {
            get {
                return ResourceManager.GetString("ACCOUNT_SCREENER_CATEGORY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not found in the application.
        /// </summary>
        internal static string ACCOUNT_USERID_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_USERID_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accout email does not exist.
        /// </summary>
        internal static string ACCOUNT_USERNAME_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_USERNAME_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login is invalid. Please review it.
        /// </summary>
        internal static string ACCOUNT_WRONG_CREDENTIALS {
            get {
                return ResourceManager.GetString("ACCOUNT_WRONG_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is invalid. Please review it.
        /// </summary>
        internal static string ACCOUNT_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("ACCOUNT_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check has been already deactivated.
        /// </summary>
        internal static string ATOMIC_CHECK_ALREADY_DEACTIVATED {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_ALREADY_DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check cannot be assigned as there is mismatching between screener category and atomic check category.
        /// </summary>
        internal static string ATOMIC_CHECK_CATEGORY_MISMATCH_ASSIGNEMENT_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_CATEGORY_MISMATCH_ASSIGNEMENT_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check cannot be forwarded to other screener.
        /// </summary>
        internal static string ATOMIC_CHECK_FORWARDED_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_FORWARDED_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert atomic check.
        /// </summary>
        internal static string ATOMIC_CHECK_INSERT_ERROR {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_INSERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check cannot be assigned as it is with the status NOT APPLICABLE.
        /// </summary>
        internal static string ATOMIC_CHECK_NOT_APPLICABLE_ASSIGNEMENT_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_NOT_APPLICABLE_ASSIGNEMENT_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of check already qualified cannot become not applicable.
        /// </summary>
        internal static string ATOMIC_CHECK_NOT_APPLICABLE_UPDATE_ERROR {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_NOT_APPLICABLE_UPDATE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check is not found.
        /// </summary>
        internal static string ATOMIC_CHECK_NOT_FOUND {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check cannot be assigned as it is not yet qualified.
        /// </summary>
        internal static string ATOMIC_CHECK_NOT_QUALIFIED_ASSIGNEMENT_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_NOT_QUALIFIED_ASSIGNEMENT_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check with status &quot;ON GOING&quot; cannot be processed and send to quality control.
        /// </summary>
        internal static string ATOMIC_CHECK_PROCESSED_CANNOT_BE_ON_GOING {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_PROCESSED_CANNOT_BE_ON_GOING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic check with status &quot;ON PROCESS FORWARDED&quot; cannot be processed and send to quality control.
        /// </summary>
        internal static string ATOMIC_CHECK_PROCESSED_CANNOT_BE_ON_PROCESS_FORWARDED {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_PROCESSED_CANNOT_BE_ON_PROCESS_FORWARDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary field is mandatory. Please fill before submitting data.
        /// </summary>
        internal static string ATOMIC_CHECK_SUMMARY_MANDATORY {
            get {
                return ResourceManager.GetString("ATOMIC_CHECK_SUMMARY_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment has not been found.
        /// </summary>
        internal static string ATTACHMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ATTACHMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an account manager.
        /// </summary>
        internal static string CLIENT_COMPANY_ACCOUNT_MANAGER_MISSING {
            get {
                return ResourceManager.GetString("CLIENT_COMPANY_ACCOUNT_MANAGER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client company is already existing.
        /// </summary>
        internal static string CLIENT_COMPANY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CLIENT_COMPANY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client company contact is already existing.
        /// </summary>
        internal static string CLIENT_COMPANY_CONTACT_PERSON_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CLIENT_COMPANY_CONTACT_PERSON_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client company contact has not been found.
        /// </summary>
        internal static string CLIENT_COMPANY_CONTACT_PERSON_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_COMPANY_CONTACT_PERSON_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client contract is already existing.
        /// </summary>
        internal static string CLIENT_COMPANY_CONTRACT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CLIENT_COMPANY_CONTRACT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client contract has not been found.
        /// </summary>
        internal static string CLIENT_COMPANY_CONTRACT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_COMPANY_CONTRACT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client company has not been found.
        /// </summary>
        internal static string CLIENT_COMPANY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_COMPANY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has not been found.
        /// </summary>
        internal static string COMMON_ADDRESS_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMMON_ADDRESS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person is already exist. Please insert the different name..
        /// </summary>
        internal static string COMMON_CONTACT_PERSON_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("COMMON_CONTACT_PERSON_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete contact person.
        /// </summary>
        internal static string COMMON_CONTACT_PERSON_DELETE_ERROR {
            get {
                return ResourceManager.GetString("COMMON_CONTACT_PERSON_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert contact person.
        /// </summary>
        internal static string COMMON_CONTACT_PERSON_INSERT_ERROR {
            get {
                return ResourceManager.GetString("COMMON_CONTACT_PERSON_INSERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person is not found.
        /// </summary>
        internal static string COMMON_CONTACT_PERSON_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMMON_CONTACT_PERSON_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Validation Error. Please kindly double check you data submission..
        /// </summary>
        internal static string COMMON_FORM_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("COMMON_FORM_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is already existing.
        /// </summary>
        internal static string COMMON_LOCATION_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("COMMON_LOCATION_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location has not been found.
        /// </summary>
        internal static string COMMON_LOCATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("COMMON_LOCATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Qualification is exist. Please enter different name..
        /// </summary>
        internal static string DBLOOKUP_PROFESSIONAL_QUALIFICATION_IS_EXIST {
            get {
                return ResourceManager.GetString("DBLOOKUP_PROFESSIONAL_QUALIFICATION_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional qualification is not found.
        /// </summary>
        internal static string DBLOOKUP_PROFESSIONAL_QUALIFICATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("DBLOOKUP_PROFESSIONAL_QUALIFICATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification is not compatible with the screening level.
        /// </summary>
        internal static string DBLOOKUP_QUALIFICATION_NOT_COMPATIBLE_WITH_SCREENING {
            get {
                return ResourceManager.GetString("DBLOOKUP_QUALIFICATION_NOT_COMPATIBLE_WITH_SCREENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification place is already deactivated.
        /// </summary>
        internal static string DBLOOKUP_QUALIFICATION_PLACE_ALREADY_DEACTIVATED {
            get {
                return ResourceManager.GetString("DBLOOKUP_QUALIFICATION_PLACE_ALREADY_DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification place is already exist.
        /// </summary>
        internal static string DBLOOKUP_QUALIFICATION_PLACE_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("DBLOOKUP_QUALIFICATION_PLACE_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete Qualification Place.
        /// </summary>
        internal static string DBLOOKUP_QUALIFICATION_PLACE_DELETE_ERROR {
            get {
                return ResourceManager.GetString("DBLOOKUP_QUALIFICATION_PLACE_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert Qualification Place.
        /// </summary>
        internal static string DBLOOKUP_QUALIFICATION_PLACE_INSERT_ERROR {
            get {
                return ResourceManager.GetString("DBLOOKUP_QUALIFICATION_PLACE_INSERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The qualification place is not found.
        /// </summary>
        internal static string DBLOOKUP_QUALIFICATION_PLACE_NOT_FOUND {
            get {
                return ResourceManager.GetString("DBLOOKUP_QUALIFICATION_PLACE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification place type is not match.
        /// </summary>
        internal static string DBLOOKUP_QUALIFICATION_PLACE_TYPE_NOT_MATCH {
            get {
                return ResourceManager.GetString("DBLOOKUP_QUALIFICATION_PLACE_TYPE_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canoot delete University.
        /// </summary>
        internal static string DBLOOKUP_UNIVERSITY_DELETE_ERROR {
            get {
                return ResourceManager.GetString("DBLOOKUP_UNIVERSITY_DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert University.
        /// </summary>
        internal static string DBLOOKUP_UNIVERSITY_INSERT_ERROR {
            get {
                return ResourceManager.GetString("DBLOOKUP_UNIVERSITY_INSERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is already exist. Please enter different name..
        /// </summary>
        internal static string DBLOOKUP_UNIVERSITY_IS_EXIST {
            get {
                return ResourceManager.GetString("DBLOOKUP_UNIVERSITY_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University is not found.
        /// </summary>
        internal static string DBLOOKUP_UNIVERSITY_NOT_FOUND {
            get {
                return ResourceManager.GetString("DBLOOKUP_UNIVERSITY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion has not been found.
        /// </summary>
        internal static string DISCUSSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("DISCUSSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not valid. Please kindly check max file size and file type..
        /// </summary>
        internal static string FILE_NOT_VALIDATED {
            get {
                return ResourceManager.GetString("FILE_NOT_VALIDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message has not been found.
        /// </summary>
        internal static string MESSAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this action.
        /// </summary>
        internal static string NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you requested is not found.
        /// </summary>
        internal static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Error.
        /// </summary>
        internal static string NO_ERROR {
            get {
                return ResourceManager.GetString("NO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public holiday is overlapping with an other already existing public holiday.
        /// </summary>
        internal static string PUBLIC_HOLIDAY_DATE_OVERLAPPING {
            get {
                return ResourceManager.GetString("PUBLIC_HOLIDAY_DATE_OVERLAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public holiday has not been found.
        /// </summary>
        internal static string PUBLIC_HOLIDAY_NOT_FOUND {
            get {
                return ResourceManager.GetString("PUBLIC_HOLIDAY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report has not been found.
        /// </summary>
        internal static string REPORT_NOT_FOUND {
            get {
                return ResourceManager.GetString("REPORT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report extension is not valid. Please upload a PDF file..
        /// </summary>
        internal static string REPORT_NOT_VALID_EXTENSION {
            get {
                return ResourceManager.GetString("REPORT_NOT_VALID_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email failure during report submition. Please send an email manually.
        /// </summary>
        internal static string REPORT_SUBMIT_MAIL_FAILURE {
            get {
                return ResourceManager.GetString("REPORT_SUBMIT_MAIL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role has already been added to the user.
        /// </summary>
        internal static string ROLE_ALREADY_BELONGS_TO_USER {
            get {
                return ResourceManager.GetString("ROLE_ALREADY_BELONGS_TO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is already existing.
        /// </summary>
        internal static string ROLE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ROLE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles of the user profile are missing.
        /// </summary>
        internal static string ROLE_MISSING {
            get {
                return ResourceManager.GetString("ROLE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role does not belong to the user.
        /// </summary>
        internal static string ROLE_NOT_BELONGS_TO_USER {
            get {
                return ResourceManager.GetString("ROLE_NOT_BELONGS_TO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has not been found.
        /// </summary>
        internal static string ROLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not belongs to screener role.
        /// </summary>
        internal static string SCREENING_ACCOUNT_NOT_BELONGS_TO_SCREENER_ROLE {
            get {
                return ResourceManager.GetString("SCREENING_ACCOUNT_NOT_BELONGS_TO_SCREENER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening has already been deactivated.
        /// </summary>
        internal static string SCREENING_ALREADY_DEACTIVATED {
            get {
                return ResourceManager.GetString("SCREENING_ALREADY_DEACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening is already exist. Please enter different name.
        /// </summary>
        internal static string SCREENING_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("SCREENING_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV File is required. Please upload a valid document..
        /// </summary>
        internal static string SCREENING_CV_FILE_REQUIRED {
            get {
                return ResourceManager.GetString("SCREENING_CV_FILE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening level is already existing for this client.
        /// </summary>
        internal static string SCREENING_LEVEL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("SCREENING_LEVEL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening level has not been found.
        /// </summary>
        internal static string SCREENING_LEVEL_NOT_FOUND {
            get {
                return ResourceManager.GetString("SCREENING_LEVEL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one type of check.
        /// </summary>
        internal static string SCREENING_LEVEL_SELECT_ANY_CHECKS {
            get {
                return ResourceManager.GetString("SCREENING_LEVEL_SELECT_ANY_CHECKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening level version is already existing for this client.
        /// </summary>
        internal static string SCREENING_LEVEL_VERSION_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("SCREENING_LEVEL_VERSION_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No screening level are available in the application. Please contact Integrity to inform them about this error.
        /// </summary>
        internal static string SCREENING_LEVEL_VERSION_NOT_EXISTING_FOR_PERIOD {
            get {
                return ResourceManager.GetString("SCREENING_LEVEL_VERSION_NOT_EXISTING_FOR_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening level version has not been found.
        /// </summary>
        internal static string SCREENING_LEVEL_VERSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("SCREENING_LEVEL_VERSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An other version of this screening level is overlapping with the information provided. Please review the date range.
        /// </summary>
        internal static string SCREENING_LEVEL_VERSION_OVERLAPPING {
            get {
                return ResourceManager.GetString("SCREENING_LEVEL_VERSION_OVERLAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening is not found.
        /// </summary>
        internal static string SCREENING_NOT_FOUND {
            get {
                return ResourceManager.GetString("SCREENING_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of check is already existing.
        /// </summary>
        internal static string TYPE_OF_CHECK_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("TYPE_OF_CHECK_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of check meta has not been found.
        /// </summary>
        internal static string TYPE_OF_CHECK_META_NOT_FOUND {
            get {
                return ResourceManager.GetString("TYPE_OF_CHECK_META_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of check has not been found.
        /// </summary>
        internal static string TYPE_OF_CHECK_NOT_FOUND {
            get {
                return ResourceManager.GetString("TYPE_OF_CHECK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has encountered in the application. Sorry for the inconvenience.
        /// </summary>
        internal static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An other leave of this user is overlapping with the information provided. Please review the data range.
        /// </summary>
        internal static string USER_LEAVE_DATE_OVERLAPPING {
            get {
                return ResourceManager.GetString("USER_LEAVE_DATE_OVERLAPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is greater than end date. Please update it.
        /// </summary>
        internal static string USER_LEAVE_DATE_RANGE_ERROR {
            get {
                return ResourceManager.GetString("USER_LEAVE_DATE_RANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User leave has not been found.
        /// </summary>
        internal static string USER_LEAVE_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_LEAVE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
