//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Qualification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Qualification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVScreeningWeb.Resources.Qualification.Qualification", typeof(Qualification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong qualification, please requalify it.
        /// </summary>
        public static string AddressWrongQualification {
            get {
                return ResourceManager.GetString("AddressWrongQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already qualified.
        /// </summary>
        public static string AlreadyQualified {
            get {
                return ResourceManager.GetString("AlreadyQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth place.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification places.
        /// </summary>
        public static string CertificationPlace {
            get {
                return ResourceManager.GetString("CertificationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification places provided.
        /// </summary>
        public static string CertificationPlaceNotApplicable {
            get {
                return ResourceManager.GetString("CertificationPlaceNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial courts.
        /// </summary>
        public static string CommercialCourts {
            get {
                return ResourceManager.GetString("CommercialCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial courts provided.
        /// </summary>
        public static string CommercialCourtsNotApplicable {
            get {
                return ResourceManager.GetString("CommercialCourtsNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies provided.
        /// </summary>
        public static string CompaniesNotApplicable {
            get {
                return ResourceManager.GetString("CompaniesNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current address.
        /// </summary>
        public static string CurrentAddress {
            get {
                return ResourceManager.GetString("CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current address provided.
        /// </summary>
        public static string CurrentAddressNotApplicable {
            get {
                return ResourceManager.GetString("CurrentAddressNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong qualification.
        /// </summary>
        public static string CurrentAddressWrongQualification {
            get {
                return ResourceManager.GetString("CurrentAddressWrongQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV address.
        /// </summary>
        public static string CVAddress {
            get {
                return ResourceManager.GetString("CVAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV address provided.
        /// </summary>
        public static string CVAddressNotApplicable {
            get {
                return ResourceManager.GetString("CVAddressNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong qualification.
        /// </summary>
        public static string CVAddressWrongQualification {
            get {
                return ResourceManager.GetString("CVAddressWrongQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District courts.
        /// </summary>
        public static string DistrictCourts {
            get {
                return ResourceManager.GetString("DistrictCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District courts provided.
        /// </summary>
        public static string DistrictCourtsNotApplicable {
            get {
                return ResourceManager.GetString("DistrictCourtsNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving license office.
        /// </summary>
        public static string DrivingLicenseOffice {
            get {
                return ResourceManager.GetString("DrivingLicenseOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving licenses office provided.
        /// </summary>
        public static string DrivingLicenseOfficesNotApplicable {
            get {
                return ResourceManager.GetString("DrivingLicenseOfficesNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact provided.
        /// </summary>
        public static string EmergencyContactIsNotApplicable {
            get {
                return ResourceManager.GetString("EmergencyContactIsNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact name.
        /// </summary>
        public static string EmergencyContactName {
            get {
                return ResourceManager.GetString("EmergencyContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency contact relationship.
        /// </summary>
        public static string EmergencyContactRelationship {
            get {
                return ResourceManager.GetString("EmergencyContactRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency phone number.
        /// </summary>
        public static string EmergencyPhoneNumber {
            get {
                return ResourceManager.GetString("EmergencyPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facuties provided.
        /// </summary>
        public static string FacultiesNotApplicable {
            get {
                return ResourceManager.GetString("FacultiesNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculties.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong qualification corrected.
        /// </summary>
        public static string HasBeenRequalified {
            get {
                return ResourceManager.GetString("HasBeenRequalified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High schools.
        /// </summary>
        public static string HighSchool {
            get {
                return ResourceManager.GetString("HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High schools provided.
        /// </summary>
        public static string HighSchoolsNotApplicable {
            get {
                return ResourceManager.GetString("HighSchoolsNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone number.
        /// </summary>
        public static string HomePhoneNumber {
            get {
                return ResourceManager.GetString("HomePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID address card provided.
        /// </summary>
        public static string IDAddressNotApplicable {
            get {
                return ResourceManager.GetString("IDAddressNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong qualification.
        /// </summary>
        public static string IDAddressWrongQualification {
            get {
                return ResourceManager.GetString("IDAddressWrongQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card address.
        /// </summary>
        public static string IDCardAddress {
            get {
                return ResourceManager.GetString("IDCardAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card number.
        /// </summary>
        public static string IdCardNumber {
            get {
                return ResourceManager.GetString("IdCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigration office.
        /// </summary>
        public static string ImmigrationOffice {
            get {
                return ResourceManager.GetString("ImmigrationOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigration office provided.
        /// </summary>
        public static string ImmigrationOfficeNotApplicable {
            get {
                return ResourceManager.GetString("ImmigrationOfficeNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial courts.
        /// </summary>
        public static string IndustrialCourts {
            get {
                return ResourceManager.GetString("IndustrialCourts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial courts provided.
        /// </summary>
        public static string IndustrialCourtsNotApplicable {
            get {
                return ResourceManager.GetString("IndustrialCourtsNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital status.
        /// </summary>
        public static string MartialStatus {
            get {
                return ResourceManager.GetString("MartialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone number.
        /// </summary>
        public static string MobilePhoneNumber {
            get {
                return ResourceManager.GetString("MobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information provided.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport number.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number provided.
        /// </summary>
        public static string PhoneNumberIsNotApplicable {
            get {
                return ResourceManager.GetString("PhoneNumberIsNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polices.
        /// </summary>
        public static string Police {
            get {
                return ResourceManager.GetString("Police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population Office.
        /// </summary>
        public static string PopulationOffice {
            get {
                return ResourceManager.GetString("PopulationOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionnal qualification.
        /// </summary>
        public static string ProfessionnalQualification {
            get {
                return ResourceManager.GetString("ProfessionnalQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification place.
        /// </summary>
        public static string QualificationPlace {
            get {
                return ResourceManager.GetString("QualificationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong qualification.
        /// </summary>
        public static string WrongQualification {
            get {
                return ResourceManager.GetString("WrongQualification", resourceCulture);
            }
        }
    }
}
