//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address:IEntity
    {
        public Address()
        {
            this.ClientCompany = new HashSet<ClientCompany>();
            this.QualificationPlace = new HashSet<QualificationPlace>();
            this.webpages_UserProfile = new HashSet<webpages_UserProfile>();
            this.CurrentAddressScreeningQualification = new HashSet<ScreeningQualification>();
            this.CVAddressScreeningQualification = new HashSet<ScreeningQualification>();
            this.IDCardAddressScreeningQualification = new HashSet<ScreeningQualification>();
            this.ContactPerson = new HashSet<ContactPerson>();
    		InitializeEntity();
        }
    
        public int AddressId { get; set; }
        public string Street { get; set; }
        public string PostalCode { get; set; }
        public byte AddressTenantId { get; set; }
    
        public virtual ICollection<ClientCompany> ClientCompany { get; set; }
        public virtual ICollection<QualificationPlace> QualificationPlace { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<webpages_UserProfile> webpages_UserProfile { get; set; }
        public virtual ICollection<ScreeningQualification> CurrentAddressScreeningQualification { get; set; }
        public virtual ICollection<ScreeningQualification> CVAddressScreeningQualification { get; set; }
        public virtual ICollection<ScreeningQualification> IDCardAddressScreeningQualification { get; set; }
        public virtual ICollection<ContactPerson> ContactPerson { get; set; }
    }
}
