//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtomicCheck:IEntity
    {
        public AtomicCheck()
        {
            this.Attachment = new HashSet<Attachment>();
            this.History = new HashSet<History>();
            this.Discussion = new HashSet<Discussion>();
            this.Permission = new HashSet<Permission>();
    		InitializeEntity();
        }
    
        public int AtomicCheckId { get; set; }
        public string AtomicCheckCategory { get; set; }
        public string AtomicCheckSummary { get; set; }
        public string AtomicCheckReport { get; set; }
        public string AtomicCheckRemarks { get; set; }
        public byte AtomicCheckTenantId { get; set; }
        public bool AtomicCheckDeactivated { get; set; }
        public byte AtomicCheckState { get; set; }
        public byte AtomicCheckValidationState { get; set; }
        public string AtomicCheckType { get; set; }
    
        public virtual QualificationPlace QualificationPlace { get; set; }
        public virtual TypeOfCheckScreeningLevelVersion TypeOfCheckScreeningLevelVersion { get; set; }
        public virtual Screening Screening { get; set; }
        public virtual webpages_UserProfile Screener { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual ICollection<History> History { get; set; }
        public virtual ICollection<Discussion> Discussion { get; set; }
        public virtual ICollection<Permission> Permission { get; set; }
    }
}
