//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment:IEntity
    {
        public int AttachmentId { get; set; }
        public string AttachmentName { get; set; }
        public Nullable<System.DateTime> AttachmentCreatedDate { get; set; }
        public string AttachmentFilePath { get; set; }
        public string AttachmentFileType { get; set; }
        public byte AttachmentTenantId { get; set; }
    
        public virtual AtomicCheck AtomicCheck { get; set; }
        public virtual Screening Screening { get; set; }
    }
}
