//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCompany:IEntity
    {
        public ClientCompany()
        {
            this.Contract = new HashSet<Contract>();
            this.ClientUserProfiles = new HashSet<webpages_UserProfile>();
            this.AccountManagers = new HashSet<webpages_UserProfile>();
            this.ContactPerson = new HashSet<ContactPerson>();
    		InitializeEntity();
        }
    
        public int ClientCompanyId { get; set; }
        public string ClientCompanyName { get; set; }
        public string Category { get; set; }
        public bool ClientCompanyIsDeactivated { get; set; }
        public string Description { get; set; }
        public byte ClientCompanyTenantId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual ICollection<webpages_UserProfile> ClientUserProfiles { get; set; }
        public virtual ICollection<webpages_UserProfile> AccountManagers { get; set; }
        public virtual ICollection<ContactPerson> ContactPerson { get; set; }
    }
}
