//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultMatrix:IEntity
    {
        public int DefaultMatrixId { get; set; }
        public int DefaultValue { get; set; }
        public byte DefaultMatrixTenantId { get; set; }
    
        public virtual webpages_UserProfile webpages_UserProfile { get; set; }
        public virtual TypeOfCheck TypeOfCheck { get; set; }
    }
}
