//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History:IEntity
    {
        public int HistoryId { get; set; }
        public string HistoryAction { get; set; }
        public System.DateTime HistoryCreatedDate { get; set; }
        public string HistoryDescription { get; set; }
        public Nullable<byte> HistoryScreeningOldStatus { get; set; }
        public Nullable<byte> HistoryScreeningNewStatus { get; set; }
        public Nullable<byte> HistoryAtomicCheckOldStatus { get; set; }
        public Nullable<byte> HistoryAtomicCheckNewStatus { get; set; }
        public byte HistoryTenantId { get; set; }
        public Nullable<byte> HistoryAtomicCheckOldValidationStatus { get; set; }
        public Nullable<byte> HistoryAtomicCheckNewValidationStatus { get; set; }
    
        public virtual AtomicCheck AtomicCheck { get; set; }
        public virtual Screening Screening { get; set; }
        public virtual webpages_UserProfile webpages_UserProfile { get; set; }
    }
}
