//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location:IEntity
    {
        public Location()
        {
            this.Address = new HashSet<Address>();
            this.LocationChildren = new HashSet<Location>();
    		InitializeEntity();
        }
    
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public int LocationLevel { get; set; }
        public byte LocationTenantId { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Location> LocationChildren { get; set; }
        public virtual Location LocationParent { get; set; }
    }
}
