//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification:IEntity
    {
        public Notification()
        {
            this.NotificationOfUser = new HashSet<NotificationOfUser>();
    		InitializeEntity();
        }
    
        public int NotificationId { get; set; }
        public string NotificationMessage { get; set; }
        public System.DateTime NotificationCreatedDate { get; set; }
        public byte NotificationTenantId { get; set; }
    
        public virtual ICollection<NotificationOfUser> NotificationOfUser { get; set; }
    }
}
