//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission:IEntity
    {
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
        public bool PermissionIsGranted { get; set; }
        public byte PermissionTenantId { get; set; }
    
        public virtual AtomicCheck AtomicCheck { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Discussion Discussion { get; set; }
        public virtual webpages_UserProfile UserProfile { get; set; }
        public virtual Screening Screening { get; set; }
        public virtual ScreeningLevel ScreeningLevel { get; set; }
        public virtual ScreeningReport ScreeningReport { get; set; }
        public virtual webpages_Roles Roles { get; set; }
        public virtual ScreeningLevelVersion ScreeningLevelVersion { get; set; }
    }
}
