//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicHoliday:IEntity
    {
        public int PublicHolidayId { get; set; }
        public string PublicHolidayName { get; set; }
        public System.DateTime PublicHolidayStartDate { get; set; }
        public System.DateTime PublicHolidayEndDate { get; set; }
        public string PublicHolidayRemarks { get; set; }
        public byte PublicHolidayTenantId { get; set; }
    }
}
