//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class QualificationPlace:IEntity
    {
        public QualificationPlace()
        {
            this.ProfessionalQualification = new HashSet<ProfessionalQualification>();
            this.Screening = new HashSet<Screening>();
            this.AtomicCheck = new HashSet<AtomicCheck>();
            this.ContactPerson = new HashSet<ContactPerson>();
            this.SkillMatrix = new HashSet<SkillMatrix>();
            this.ScreeningQualificationPlaceMeta = new HashSet<ScreeningQualificationPlaceMeta>();
    		InitializeEntity();
        }
    
        public int QualificationPlaceId { get; set; }
        public string QualificationPlaceName { get; set; }
        public string QualificationPlaceCategory { get; set; }
        public string QualificationPlaceDescription { get; set; }
        public string QualificationPlaceWebSite { get; set; }
        public bool QualificationPlaceIsDeactivated { get; set; }
        public byte QualificationPlaceTenantId { get; set; }
        public string QualificationPlaceAlumniWebSite { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<ProfessionalQualification> ProfessionalQualification { get; set; }
        public virtual ICollection<Screening> Screening { get; set; }
        public virtual University University { get; set; }
        public virtual ICollection<AtomicCheck> AtomicCheck { get; set; }
        public virtual ICollection<ContactPerson> ContactPerson { get; set; }
        public virtual ICollection<SkillMatrix> SkillMatrix { get; set; }
        public virtual ICollection<ScreeningQualificationPlaceMeta> ScreeningQualificationPlaceMeta { get; set; }
    }
}
