//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening:IEntity
    {
        public Screening()
        {
            this.QualificationPlace = new HashSet<QualificationPlace>();
            this.AtomicCheck = new HashSet<AtomicCheck>();
            this.Attachment = new HashSet<Attachment>();
            this.ScreeningReport = new HashSet<ScreeningReport>();
            this.History = new HashSet<History>();
            this.Discussion = new HashSet<Discussion>();
            this.Permission = new HashSet<Permission>();
            this.ScreeningQualificationPlaceMeta = new HashSet<ScreeningQualificationPlaceMeta>();
    		InitializeEntity();
        }
    
        public int ScreeningId { get; set; }
        public string ScreeningReference { get; set; }
        public string ScreeningComments { get; set; }
        public Nullable<System.DateTime> ScreeningUploadedDate { get; set; }
        public Nullable<System.DateTime> ScreeningStartingDate { get; set; }
        public Nullable<System.DateTime> ScreeningDeadlineDate { get; set; }
        public Nullable<System.DateTime> ScreeningDeliveryDate { get; set; }
        public Nullable<System.DateTime> ScreeningLastUpdatedDate { get; set; }
        public string ScreeningAdditionalRemarks { get; set; }
        public bool ScreeningIsDeactivated { get; set; }
        public byte ScreeningTenantId { get; set; }
        public byte ScreeningState { get; set; }
        public int ScreeningQualificationId { get; set; }
        public string ScreeningFullName { get; set; }
        public string ScreeningPhysicalPath { get; set; }
        public string ScreeningVirtualPath { get; set; }
    
        public virtual ScreeningQualification ScreeningQualification { get; set; }
        public virtual ICollection<QualificationPlace> QualificationPlace { get; set; }
        public virtual webpages_UserProfile QualityControl { get; set; }
        public virtual ICollection<AtomicCheck> AtomicCheck { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual ICollection<ScreeningReport> ScreeningReport { get; set; }
        public virtual ICollection<History> History { get; set; }
        public virtual ICollection<Discussion> Discussion { get; set; }
        public virtual ICollection<Permission> Permission { get; set; }
        public virtual ICollection<ScreeningQualificationPlaceMeta> ScreeningQualificationPlaceMeta { get; set; }
        public virtual ScreeningLevelVersion ScreeningLevelVersion { get; set; }
    }
}
