//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningLevel:IEntity
    {
        public ScreeningLevel()
        {
            this.Permission = new HashSet<Permission>();
            this.ScreeningLevelVersion = new HashSet<ScreeningLevelVersion>();
    		InitializeEntity();
        }
    
        public int ScreeningLevelId { get; set; }
        public string ScreeningLevelName { get; set; }
        public byte ScreeningLevelTenantId { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ICollection<Permission> Permission { get; set; }
        public virtual ICollection<ScreeningLevelVersion> ScreeningLevelVersion { get; set; }
    }
}
