//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningQualification:IEntity
    {
        public int ScreeningQualificationId { get; set; }
        public string ScreeningQualificationMaritalStatus { get; set; }
        public Nullable<System.DateTime> ScreeningQualificationBirthDate { get; set; }
        public string ScreeningQualificationBirthPlace { get; set; }
        public string ScreeningQualificationGender { get; set; }
        public string ScreeningQualificationIDCardNumber { get; set; }
        public string ScreeningQualificationPassportNumber { get; set; }
        public string ScreeningQualificationRelationshipWithCandidate { get; set; }
        public Nullable<bool> ScreeningQualificationIsDeactivated { get; set; }
        public byte ScreeningQualificationTenantId { get; set; }
    
        public virtual Screening Screening { get; set; }
        public virtual ContactInfo PersonalContactInfo { get; set; }
        public virtual Address CurrentAddress { get; set; }
        public virtual Address CVAddress { get; set; }
        public virtual Address IDCardAddress { get; set; }
        public virtual ContactPerson EmergencyContactPerson { get; set; }
    }
}
