//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningLevelVersion:IEntity
    {
        public ScreeningLevelVersion()
        {
            this.Permission = new HashSet<Permission>();
            this.Screening = new HashSet<Screening>();
            this.TypeOfCheckScreeningLevelVersion = new HashSet<TypeOfCheckScreeningLevelVersion>();
    		InitializeEntity();
        }
    
        public int ScreeningLevelVersionId { get; set; }
        public int ScreeningLevelVersionNumber { get; set; }
        public string ScreeningLevelVersionDescription { get; set; }
        public System.DateTime ScreeningLevelVersionStartDate { get; set; }
        public System.DateTime ScreeningLevelVersionEndDate { get; set; }
        public int ScreeningLevelVersionTurnaroundTime { get; set; }
        public bool ScreeningLevelVersionAllowedToContactCandidate { get; set; }
        public string ScreeningLevelVersionAllowedToContactCurrentCompany { get; set; }
        public string ScreeningLevelVersionLanguage { get; set; }
        public byte ScreeningLevelVersionTenantId { get; set; }
    
        public virtual ICollection<Permission> Permission { get; set; }
        public virtual ICollection<Screening> Screening { get; set; }
        public virtual ScreeningLevel ScreeningLevel { get; set; }
        public virtual ICollection<TypeOfCheckScreeningLevelVersion> TypeOfCheckScreeningLevelVersion { get; set; }
    }
}
