//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningReport:IEntity
    {
        public ScreeningReport()
        {
            this.Permission = new HashSet<Permission>();
    		InitializeEntity();
        }
    
        public int ScreeningReportId { get; set; }
        public Nullable<int> ScreeningReportVersion { get; set; }
        public byte[] ScreeningReportContent { get; set; }
        public string ScreeningReportUrl { get; set; }
        public Nullable<System.DateTime> ScreeningReportSubmittedDate { get; set; }
        public byte ScreeningReportTenantId { get; set; }
        public string ScreeningReportFilePath { get; set; }
        public string ScreeningReportGenerationType { get; set; }
    
        public virtual Screening Screening { get; set; }
        public virtual ICollection<Permission> Permission { get; set; }
    }
}
