//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningQualificationPlaceMeta:IEntity
    {
        public int ScreeningQualificationMetaId { get; set; }
        public string ScreeningQualificationMetaKey { get; set; }
        public string ScreeningQualificationMetaValue { get; set; }
        public byte ScreeningQualificationMetaTenantId { get; set; }
    
        public virtual QualificationPlace QualificationPlace { get; set; }
        public virtual Screening Screening { get; set; }
    }
}
