//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillMatrix:IEntity
    {
        public int SkillMatrixId { get; set; }
        public int SkillValue { get; set; }
        public byte SkillMatrixTenantId { get; set; }
        public int SkillMeta { get; set; }
    
        public virtual QualificationPlace QualificationPlace { get; set; }
        public virtual webpages_UserProfile webpages_UserProfile { get; set; }
    }
}
