//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfCheckMeta:IEntity
    {
        public int TypeOfCheckMetaId { get; set; }
        public string TypeOfCheckMetaKey { get; set; }
        public string TypeOfCheckMetaValue { get; set; }
        public byte TypeOfCheckMetaTenantId { get; set; }
        public string TypeOfCheckMetaCategory { get; set; }
    
        public virtual TypeOfCheck TypeOfCheck { get; set; }
    }
}
