//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfCheck:IEntity
    {
        public TypeOfCheck()
        {
            this.TypeOfCheckMeta = new HashSet<TypeOfCheckMeta>();
            this.TypeOfCheckScreeningLevelVersion = new HashSet<TypeOfCheckScreeningLevelVersion>();
            this.DefaultMatrix = new HashSet<DefaultMatrix>();
    		InitializeEntity();
        }
    
        public int TypeOfCheckId { get; set; }
        public string CheckName { get; set; }
        public byte TypeOfCheckTenantId { get; set; }
        public byte TypeOfCheckCode { get; set; }
    
        public virtual ICollection<TypeOfCheckMeta> TypeOfCheckMeta { get; set; }
        public virtual ICollection<TypeOfCheckScreeningLevelVersion> TypeOfCheckScreeningLevelVersion { get; set; }
        public virtual ICollection<DefaultMatrix> DefaultMatrix { get; set; }
    }
}
