//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfCheckScreeningLevelVersion:IEntity
    {
        public TypeOfCheckScreeningLevelVersion()
        {
            this.AtomicCheck = new HashSet<AtomicCheck>();
    		InitializeEntity();
        }
    
        public int TypeOfCheckId { get; set; }
        public int ScreeningLevelVersionId { get; set; }
        public string TypeOfCheckScreeningComments { get; set; }
        public byte TypeOfCheckScreeningTenantId { get; set; }
    
        public virtual TypeOfCheck TypeOfCheck { get; set; }
        public virtual ICollection<AtomicCheck> AtomicCheck { get; set; }
        public virtual ScreeningLevelVersion ScreeningLevelVersion { get; set; }
    }
}
