//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class University:IEntity
    {
        public University()
        {
            this.QualificationPlace = new HashSet<QualificationPlace>();
    		InitializeEntity();
        }
    
        public int UniversityId { get; set; }
        public string UniversityName { get; set; }
        public string UniversityWebSite { get; set; }
        public byte UniversityTenantId { get; set; }
    
        public virtual ICollection<QualificationPlace> QualificationPlace { get; set; }
    }
}
