//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeave:IEntity
    {
        public int UserLeaveId { get; set; }
        public string UserLeaveName { get; set; }
        public string UserLeaveRemarks { get; set; }
        public System.DateTime UserLeaveStartDate { get; set; }
        public System.DateTime UserLeaveEndDate { get; set; }
        public byte UserLeaveTenantId { get; set; }
    
        public virtual webpages_UserProfile webpages_UserProfile { get; set; }
    }
}
