//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningService.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVScreeningService.Resources.Notification.Notification", typeof(Notification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/AtomicCheck/Edit/{0}&apos; target=&apos;_blank&apos;&gt;A new atomic check {0} has been assigned to you&lt;/a&gt;.
        /// </summary>
        public static string AtomicCheckAssigned {
            get {
                return ResourceManager.GetString("AtomicCheckAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/AtomicCheck/Edit/{0}&apos; target=&apos;_blank&apos;&gt;Atomic check {0} has been processed&lt;/a&gt;.
        /// </summary>
        public static string AtomicCheckProcessed {
            get {
                return ResourceManager.GetString("AtomicCheckProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/AtomicCheck/Edit/{0}&apos; target=&apos;_blank&apos;&gt;Atomic check {0} has been rejected by quality control &lt;/a&gt;.
        /// </summary>
        public static string AtomicCheckRejected {
            get {
                return ResourceManager.GetString("AtomicCheckRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/AtomicCheck/Edit/{0}&apos; target=&apos;_blank&apos;&gt;Atomic check {0} has been validated by Quality Control&lt;/a&gt;.
        /// </summary>
        public static string AtomicCheckValidated {
            get {
                return ResourceManager.GetString("AtomicCheckValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/AtomicCheck/Edit/{0}&apos; target=&apos;_blank&apos;&gt;Atomic check {0} has been wrongly qualify by screener&lt;/a&gt;.
        /// </summary>
        public static string AtomicCheckWrongQualified {
            get {
                return ResourceManager.GetString("AtomicCheckWrongQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/AtomicCheck/Edit/{0}&apos; target=&apos;_blank&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string EditAtomicCheckLink {
            get {
                return ResourceManager.GetString("EditAtomicCheckLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/Report/ManageReport/{0}&apos; target=&apos;_blank&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string ManageReportLink {
            get {
                return ResourceManager.GetString("ManageReportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening {0} has been uploaded and needs to be qualified.
        /// </summary>
        public static string ScreeningCreated {
            get {
                return ResourceManager.GetString("ScreeningCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;/Screening/Detail/{0}&apos; target=&apos;_blank&apos;&gt;{1}&lt;/a&gt;.
        /// </summary>
        public static string ScreeningDetailLink {
            get {
                return ResourceManager.GetString("ScreeningDetailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening report {0} has been submitted.
        /// </summary>
        public static string ScreeningSubmitted {
            get {
                return ResourceManager.GetString("ScreeningSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening {0} has been validated and is ready to be submitted.
        /// </summary>
        public static string ScreeningValidated {
            get {
                return ResourceManager.GetString("ScreeningValidated", resourceCulture);
            }
        }
    }
}
