//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Screening {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Screening() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVScreeningWeb.Resources.Screening.Screening", typeof(Screening).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additionnal Remarks.
        /// </summary>
        public static string AdditionnalRemarks {
            get {
                return ResourceManager.GetString("AdditionnalRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic Check.
        /// </summary>
        public static string AtomicCheck {
            get {
                return ResourceManager.GetString("AtomicCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Uploaded.
        /// </summary>
        public static string AttachmentsAlreadyUploaded {
            get {
                return ResourceManager.GetString("AttachmentsAlreadyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a screening.
        /// </summary>
        public static string CreateScreening {
            get {
                return ResourceManager.GetString("CreateScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum Vitae.
        /// </summary>
        public static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string DayPending {
            get {
                return ResourceManager.GetString("DayPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery ending date.
        /// </summary>
        public static string DeliveryEndingDate {
            get {
                return ResourceManager.GetString("DeliveryEndingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery starting date.
        /// </summary>
        public static string DeliveryStartingDate {
            get {
                return ResourceManager.GetString("DeliveryStartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Atomic Checks.
        /// </summary>
        public static string DispatchAtomicChecks {
            get {
                return ResourceManager.GetString("DispatchAtomicChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Atomic Check.
        /// </summary>
        public static string ManageAtomicCheck {
            get {
                return ResourceManager.GetString("ManageAtomicCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Report.
        /// </summary>
        public static string ManageReport {
            get {
                return ResourceManager.GetString("ManageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualify.
        /// </summary>
        public static string Qualify {
            get {
                return ResourceManager.GetString("Qualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control.
        /// </summary>
        public static string QualityControl {
            get {
                return ResourceManager.GetString("QualityControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Level.
        /// </summary>
        public static string ScreeningLevel {
            get {
                return ResourceManager.GetString("ScreeningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Level Version.
        /// </summary>
        public static string ScreeningLevelVersion {
            get {
                return ResourceManager.GetString("ScreeningLevelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening name.
        /// </summary>
        public static string ScreeningName {
            get {
                return ResourceManager.GetString("ScreeningName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Screening.
        /// </summary>
        public static string SearchScreening {
            get {
                return ResourceManager.GetString("SearchScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select client company ....
        /// </summary>
        public static string SelectClientCompany {
            get {
                return ResourceManager.GetString("SelectClientCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select contract ....
        /// </summary>
        public static string SelectContract {
            get {
                return ResourceManager.GetString("SelectContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select screening level ....
        /// </summary>
        public static string SelectScreeningLevel {
            get {
                return ResourceManager.GetString("SelectScreeningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select screening level version ....
        /// </summary>
        public static string SelectScreeningLevelVersion {
            get {
                return ResourceManager.GetString("SelectScreeningLevelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Date.
        /// </summary>
        public static string SubmittedDate {
            get {
                return ResourceManager.GetString("SubmittedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Check.
        /// </summary>
        public static string TypeOfCheck {
            get {
                return ResourceManager.GetString("TypeOfCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Manual Report.
        /// </summary>
        public static string UploadManualReport {
            get {
                return ResourceManager.GetString("UploadManualReport", resourceCulture);
            }
        }
    }
}
