//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningDAL.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using CVScreeningCore.Models;
    
    public partial class CVScreeningEFContext : DbContext
    {
        public CVScreeningEFContext()
            : base("name=CVScreeningEFContextConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Address { get; set; }
        public DbSet<ClientCompany> ClientCompany { get; set; }
        public DbSet<ContactInfo> ContactInfo { get; set; }
        public DbSet<Contract> Contract { get; set; }
        public DbSet<ProfessionalQualification> ProfessionalQualification { get; set; }
        public DbSet<PublicHoliday> PublicHoliday { get; set; }
        public DbSet<QualificationPlace> QualificationPlace { get; set; }
        public DbSet<Screening> Screening { get; set; }
        public DbSet<ScreeningLevel> ScreeningLevel { get; set; }
        public DbSet<ScreeningQualification> ScreeningQualification { get; set; }
        public DbSet<TypeOfCheck> TypeOfCheck { get; set; }
        public DbSet<TypeOfCheckMeta> TypeOfCheckMeta { get; set; }
        public DbSet<University> University { get; set; }
        public DbSet<UserLeave> UserLeave { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<webpages_UserProfile> webpages_UserProfile { get; set; }
        public DbSet<TypeOfCheckScreeningLevelVersion> TypeOfCheckScreeningLevelVersion { get; set; }
        public DbSet<Tenant> Tenant { get; set; }
        public DbSet<AtomicCheck> AtomicCheck { get; set; }
        public DbSet<Attachment> Attachment { get; set; }
        public DbSet<ScreeningReport> ScreeningReport { get; set; }
        public DbSet<History> History { get; set; }
        public DbSet<Discussion> Discussion { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<ContactPerson> ContactPerson { get; set; }
        public DbSet<DefaultMatrix> DefaultMatrix { get; set; }
        public DbSet<Permission> Permission { get; set; }
        public DbSet<SkillMatrix> SkillMatrix { get; set; }
        public DbSet<Notification> Notification { get; set; }
        public DbSet<NotificationOfUser> NotificationOfUser { get; set; }
        public DbSet<DispatchingSettings> DispatchingSettings { get; set; }
        public DbSet<ScreeningQualificationPlaceMeta> ScreeningQualificationPlaceMeta { get; set; }
        public DbSet<ScreeningLevelVersion> ScreeningLevelVersion { get; set; }
    }
}
