//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dispatching {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dispatching() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVScreeningWeb.Resources.Dispatching.Dispatching", typeof(Dispatching).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Category.
        /// </summary>
        public static string CategoryFilter {
            get {
                return ResourceManager.GetString("CategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Column.
        /// </summary>
        public static string ColumnFilter {
            get {
                return ResourceManager.GetString("ColumnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Default Value.
        /// </summary>
        public static string ManageDefaultValue {
            get {
                return ResourceManager.GetString("ManageDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatching.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row.
        /// </summary>
        public static string RowFilter {
            get {
                return ResourceManager.GetString("RowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Screener Category.
        /// </summary>
        public static string ScreenerCategoryFilter {
            get {
                return ResourceManager.GetString("ScreenerCategoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select place to display.
        /// </summary>
        public static string SelectPlace {
            get {
                return ResourceManager.GetString("SelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select place category to display.
        /// </summary>
        public static string SelectPlaceType {
            get {
                return ResourceManager.GetString("SelectPlaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select screener category to display.
        /// </summary>
        public static string SelectScreenerCategory {
            get {
                return ResourceManager.GetString("SelectScreenerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select screeners to display.
        /// </summary>
        public static string SelectScreeners {
            get {
                return ResourceManager.GetString("SelectScreeners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select type of checks to display.
        /// </summary>
        public static string SelectTypeOfChecks {
            get {
                return ResourceManager.GetString("SelectTypeOfChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Matrix.
        /// </summary>
        public static string SkillMatrix {
            get {
                return ResourceManager.GetString("SkillMatrix", resourceCulture);
            }
        }
    }
}
