//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address:IEntity
    {
        public void SetId(int id)
        {
            AddressId = id;
        }

        public int GetId()
        {
            return AddressId;
        }

        public void SetTenantId(byte id)
        {
            AddressTenantId = id;
        }

        public byte GetTenantId()
        {
            return AddressTenantId;
        }

        public void InitializeEntity()
        {
            
        }

        /// <summary>
        /// Returns true whether the location is set or not
        /// </summary>
        /// <returns></returns>
        public bool IsSet()
        {
            // Indonesian address
            if (!String.IsNullOrEmpty(Street) && (!String.IsNullOrEmpty(PostalCode))
                && Location != null && Location.LocationId != 0)
                return true;

            // Other address
            if (!String.IsNullOrEmpty(Street) && Location != null && Location.IsCountry())
                return true;

            return false;
        }

        /// <summary>
        /// Override to string function
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return string.Format("Address POCO object: Street: {0}, " +
                                 "Postal code: {1}, LocationId: {2}",
                                 Street, PostalCode, Location != null ? Location.LocationId.ToString(): "null");
        }
    }
}
