//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment:IEntity
    {
        public void SetId(int id)
        {
            AttachmentId = id;
        }


        public int GetId()
        {
            return AttachmentId;
        }

        public void SetTenantId(byte id)
        {
            AttachmentTenantId = id;
        }

        public byte GetTenantId()
        {
            return AttachmentTenantId;
        }

        public void InitializeEntity()
        {

        }

        public int GetClientCompanyId()
        {
            if (this.Screening != null)
                return this.Screening.ScreeningLevelVersion.ScreeningLevel.Contract.ClientCompany.ClientCompanyId;
            return 0;
        }
    }
}
