//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company:QualificationPlace , IEntity
    {
        /// <summary>
        /// Retrieve all the type of checks compatible with this qualification place
        /// </summary>
        /// <returns></returns>
        public override IEnumerable<TypeOfCheckEnum> GetTypeOfChecksCompatible()
        {
            return new List<TypeOfCheckEnum>
            {
                TypeOfCheckEnum.EMPLOYMENT_CHECK_STANDARD,
                TypeOfCheckEnum.EMPLOYMENT_CHECK_PERFORMANCE,
            };
        }

        public override QualificationCode GetQualificationCode()
        {
            return QualificationCode.Company;
        }

        public override bool IsCurrentCompanyForScreening(Screening screening)
        {
            return this.ScreeningQualificationPlaceMeta.First(
                u => u.Screening == screening && u.ScreeningQualificationMetaKey ==
                     Models.ScreeningQualificationPlaceMeta.kIsCurrentCompany).ScreeningQualificationMetaValue == Models.ScreeningQualificationPlaceMeta.kYesValue;
        }
    }
}
