//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract:IEntity
    {

        #region IEntity interface method definition

        public void SetId(int id)
        {
            ContractId = id;
        }

        public int GetId()
        {
            return ContractId;
        }

        public void SetTenantId(byte id)
        {
            ContractTenantId = id;
        }

        public byte GetTenantId()
        {
            return ContractTenantId;
        }

        public void InitializeEntity()
        {

        }

        #endregion

        #region Permission

        /// <summary>
        /// Add permission for this contract
        /// </summary>
        /// <param name="userProfile"></param>
        /// <param name="permissionName"></param>
        private void GrantPermission(webpages_UserProfile userProfile, string permissionName)
        {
            if (!this.Permission.Any(p => p.Contract == this && p.UserProfile == userProfile
                                          && p.PermissionName == permissionName && p.PermissionIsGranted == true))
            {
                this.Permission.Add(new Permission
                {
                    Contract = this,
                    UserProfile = userProfile,
                    PermissionName = permissionName,
                    PermissionIsGranted = true
                });
            }
        }

        /// <summary>
        /// Revoke permission for this contract
        /// </summary>
        /// <param name="userProfile"></param>
        /// <param name="permissionName"></param>
        private void RevokePermission(webpages_UserProfile userProfile, string permissionName)
        {
            this.Permission.Reverse().Where(p => p.Contract == this && p.UserProfile == userProfile
                && p.PermissionName == permissionName).ToList().ForEach(z => this.Permission.Remove(z));
        }

        /// <summary>
        /// Setup contract view permission
        /// </summary>
        /// <param name="userProfile"></param>
        public void GrantContractViewPermission(webpages_UserProfile userProfile)
        {
            GrantPermission(userProfile, Models.Permission.kContractViewPermission);
        }

        /// <summary>
        /// Setup contract view permission
        /// </summary>
        /// <param name="userProfile"></param>
        public void RevokeContractViewPermission(webpages_UserProfile userProfile)
        {
            RevokePermission(userProfile, Models.Permission.kContractViewPermission);
        }

        /// <summary>
        /// Grant permission to all account manager
        /// </summary>
        public void GrantPermissionForAllAccountManagers()
        {
            foreach (var accountManager in this.ClientCompany.AccountManagers)
            {
                GrantContractViewPermission(accountManager);
            }
        }

        /// <summary>
        /// Grant permission to all client of this contract
        /// </summary>
        public void GrantPermissionForAllClients()
        {
            foreach (var client in this.ClientCompany.ClientUserProfiles)
            {
                GrantContractViewPermission(client);
            }
        }

        /// <summary>
        /// Revoke permission to all account manager
        /// </summary>
        public void RevokePermissionForAllAccountManagers()
        {
            foreach (var accountManager in this.ClientCompany.AccountManagers)
            {
                RevokeContractViewPermission(accountManager);
            }
        }

        /// <summary>
        /// Grant permission to all client of this contract
        /// </summary>
        public void RevokePermissionForAllClients()
        {
            foreach (var client in this.ClientCompany.ClientUserProfiles)
            {
                RevokeContractViewPermission(client);
            }
        }

        #endregion

        public IEnumerable<Screening> GetAllScreenings()
        {
            var screenings = new List<Screening>();
            foreach (var screeningLevel in this.ScreeningLevel)
            {
                screenings.AddRange(screeningLevel.GetAllScreenings());
            }
            return screenings;
        } 
    }
}
