//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court:QualificationPlace , IEntity
    {
        /// <summary>
        /// Retrieve all the type of checks compatible with this qualification place
        /// </summary>
        /// <returns></returns>
        public override IEnumerable<TypeOfCheckEnum> GetTypeOfChecksCompatible()
        {
            if (this.QualificationPlaceCategory == "District")
                return new List<TypeOfCheckEnum>
                {
                    TypeOfCheckEnum.LITIGATION_CHECK_CIVIL,
                    TypeOfCheckEnum.LITIGATION_CHECK_CRIMINAL,
                    TypeOfCheckEnum.LITIGATION_CHECK_CIVIL_CRIMINAL,
                };

            else if (this.QualificationPlaceCategory == "Commercial")
                return new List<TypeOfCheckEnum>
                {
                    TypeOfCheckEnum.BANKRUPTY_CHECK,
                };

            else if (this.QualificationPlaceCategory == "Industrial")
                return new List<TypeOfCheckEnum>
                {
                    TypeOfCheckEnum.INDUSTRIAL_CHECK,
                };
            return new List<TypeOfCheckEnum>();

        }

        public override QualificationCode GetQualificationCode()
        {
            return QualificationCode.Court;
        }
    }
}
