//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location:IEntity
    {
        public void SetId(int id)
        {
            LocationId = id;
        }

        public int GetId()
        {
            return LocationId;
        }

        public void SetTenantId(byte id)
        {
            LocationId = id;
        }

        public byte GetTenantId()
        {
            return LocationTenantId;
        }

        public void InitializeEntity()
        {

        }
        
        /// <summary>
        /// Returns true whether this location is a country or not
        /// </summary>
        /// <returns></returns>
        public bool IsCountry()
        {
            return this.LocationLevel == 1;
        }

        /// <summary>
        /// Returns true whether this location is a province or not
        /// </summary>
        /// <returns></returns>
        public bool IsProvince()
        {
            return this.LocationLevel == 2;
        }

        /// <summary>
        /// Returns true whether this location is a city or not
        /// </summary>
        /// <returns></returns>
        public bool IsCity()
        {
            return this.LocationLevel == 3;
        }

        /// <summary>
        /// Returns true whether this location is a district or not
        /// </summary>
        /// <returns></returns>
        public bool IsDistrict()
        {
            return this.LocationLevel == 4;
        }

        /// <summary>
        /// Returns true whether this location is a subdistrict or not
        /// </summary>
        /// <returns></returns>
        public bool IsSubDistrict()
        {
            return this.LocationLevel == 5;
        }
    }
}
