//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationOfUser:IEntity
    {
        #region IEntity interface method definition

        public void SetId(int id)
        {
        }

        public int GetId()
        {
            throw new NotImplementedException();
        }

        public void SetTenantId(byte id)
        {
            NotificationOfUserTenantId = id;
        }

        public byte GetTenantId()
        {
            return NotificationOfUserTenantId;
        }

        public void InitializeEntity()
        {

        }

        #endregion
    }
}
