//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission : IEntity
    {
        #region Constant permission

        public const string kScreeningCreatePermission = "ScreeningCreatePermission";
        public const string kScreeningManagePermission = "ScreeningManagePermission";
        public const string kScreeningDeactivatePermission = "ScreeningDeactivatePermission";
        public const string kScreeningViewPermission = "ScreeningViewPermission";
        public const string kScreeningLevelViewPermission = "ScreeningLevelViewPermission";
        public const string kScreeningLevelVersionViewPermission = "ScreeningLevelVersionViewPermission";
        public const string kContractViewPermission = "ContractViewPermission";
        public const string kAtomicCheckManagePermission = "AtomicCheckManagePermission";
        public const string kAtomicCheckAssignPermission = "AtomicCheckAssignPermission";
        public const string kAtomicCheckViewPermission = "AtomicCheckViewPermission";
        public const string kReportUploadPermission = "ReportUploadPermission";
        public const string kReportManagePermission = "ReportManagePermission";
        public const string kReportViewPermission = "ReportViewPermission";
        public const string kInternalScreeningDiscussionManagePermission = "InternalScreeningDiscussionManagePermission";
        public const string kExternalScreeningDiscussionManagePermission = "ExternalScreeningDiscussionManagePermission";
        public const string kInternalAtomicCheckDiscussionManagePermission = "InternalAtomicCheckDiscussionManagePermission";

        
        #endregion


        #region IEntity interface method definition

        public void SetId(int id)
        {
            PermissionId = id;
        }

        public int GetId()
        {
            return PermissionId;
        }

        public void SetTenantId(byte id)
        {
            PermissionTenantId = id;
        }

        public byte GetTenantId()
        {
            return PermissionTenantId;
        }

        public void InitializeEntity()
        {

        }

        #endregion

    }
}
