//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;

    public enum QualificationCode
    {
        Court = 1,
        Police,
        Faculty,
        Highschool,
        DrivingLicenseOffice,
        ImmigrationOffice,
        Company,
        CertificationPlace,
        QualificationPlace,
        PopulationOffice
    }

    public abstract partial class QualificationPlace:IEntity
    {
        public void SetId(int id)
        {
            QualificationPlaceId = id;
        }

        public int GetId()
        {
            return QualificationPlaceId;
        }

        public void SetTenantId(byte id)
        {
            QualificationPlaceTenantId = id;
        }

        public byte GetTenantId()
        {
            return QualificationPlaceTenantId;
        }

        public void InitializeEntity()
        {

        }

        /// <summary>
        /// Retrieve all the type of checks compatible with this qualification place
        /// </summary>
        /// <returns></returns>
        public virtual IEnumerable<TypeOfCheckEnum> GetTypeOfChecksCompatible()
        {
            throw new NotImplementedException();
        }

        public virtual QualificationCode GetQualificationCode()
        {
            throw new NotImplementedException();
        }

        public virtual bool IsCurrentCompanyForScreening(Screening screening)
        {
            throw new NotImplementedException();
        }
        
    }
}
