//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreeningLevel:IEntity
    {
        #region IEntity interface method definition

        public void SetId(int id)
        {
            ScreeningLevelId = id;
        }

        public int GetId()
        {
            return ScreeningLevelId;
        }

        public void SetTenantId(byte id)
        {
            ScreeningLevelTenantId = id;
        }

        public byte GetTenantId()
        {
            return ScreeningLevelTenantId;
        }

        public void InitializeEntity()
        {

        }

        #endregion

        #region Permission

        /// <summary>
        /// Add permission for this screening level
        /// </summary>
        /// <param name="userProfile"></param>
        /// <param name="permissionName"></param>
        private void GrantPermission(webpages_UserProfile userProfile, string permissionName)
        {
            if (!this.Permission.Any(p => p.ScreeningLevel == this && p.UserProfile == userProfile
                                          && p.PermissionName == permissionName && p.PermissionIsGranted == true))
            {
                this.Permission.Add(new Permission
                {
                    ScreeningLevel = this,
                    UserProfile = userProfile,
                    PermissionName = permissionName,
                    PermissionIsGranted = true
                });
            }
        }

        /// <summary>
        /// Revoke permission for this screening level
        /// </summary>
        /// <param name="userProfile"></param>
        /// <param name="permissionName"></param>
        private void RevokePermission(webpages_UserProfile userProfile, string permissionName)
        {
            this.Permission.Reverse().Where(p => p.ScreeningLevel == this && p.UserProfile == userProfile
                && p.PermissionName == permissionName).ToList().ForEach(z => this.Permission.Remove(z));
        }

        /// <summary>
        /// Grant screening level view permission
        /// </summary>
        /// <param name="userProfile"></param>
        public void GrantScreeningLevelViewPermission(webpages_UserProfile userProfile)
        {
            GrantPermission(userProfile, Models.Permission.kScreeningLevelViewPermission);
        }

        /// <summary>
        /// Setup screening level view permission
        /// </summary>
        /// <param name="userProfile"></param>
        public void RevokeScreeningLevelViewPermission(webpages_UserProfile userProfile)
        {
            RevokePermission(userProfile, Models.Permission.kScreeningLevelViewPermission);
        }


        /// <summary>
        /// Grant permission to all account manager
        /// </summary>
        public void GrantPermissionForAllAccountManagers()
        {
            foreach (var accountManager in this.Contract.ClientCompany.AccountManagers)
            {
                GrantScreeningLevelViewPermission(accountManager);
            }
        }

        /// <summary>
        /// Grant permission to all client of this contract
        /// </summary>
        public void GrantPermissionForAllClients()
        {
            foreach (var client in this.Contract.ClientCompany.ClientUserProfiles)
            {
                GrantScreeningLevelViewPermission(client);
            }
        }

        /// <summary>
        /// Revoke permission to all account manager
        /// </summary>
        public void RevokePermissionForAllAccountManagers()
        {
            foreach (var accountManager in this.Contract.ClientCompany.AccountManagers)
            {
                RevokeScreeningLevelViewPermission(accountManager);
            }
        }

        /// <summary>
        /// Grant permission to all client of this contract
        /// </summary>
        public void RevokePermissionForAllClients()
        {
            foreach (var client in this.Contract.ClientCompany.ClientUserProfiles)
            {
                RevokeScreeningLevelViewPermission(client);
            }
        }

        #endregion

        public ICollection<Screening> GetAllScreenings()
        {
            var screenings = new List<Screening>();
            foreach (var screeningLevelVersion in this.ScreeningLevelVersion)
            {
                screenings.AddRange(screeningLevelVersion.GetAllScreenings());
            }
            return screenings;
        }
    }
}
