//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ScreeningQualificationPlaceMeta : IEntity
    {
        public const string kIsCurrentCompany = "IsCurrentCompanyForScreening";
        public const string kYesValue = "Yes";
        public const string kNoValue = "No";


        public void SetId(int id)
        {
            ScreeningQualificationMetaId = id;
        }


        public int GetId()
        {
            return ScreeningQualificationMetaId;
        }

        public void SetTenantId(byte id)
        {
            ScreeningQualificationMetaTenantId = id;
        }

        public byte GetTenantId()
        {
            return ScreeningQualificationMetaTenantId;
        }

        public void InitializeEntity()
        {

        }
    }
}
