//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfCheckMeta:IEntity
    {
        #region Constant atomic check

        /// <summary>
        /// Metadata type of check key used to retrieve average completion rate of an type of check
        /// </summary>
        public const string kAverageCompletionRateKey = "AVERAGE_COMPLETION_RATE";

        /// <summary>
        /// Metadata type of check key used to retrieve completion minimum working days of an atomic check
        /// </summary>
        public const string kCompletionMinimumWorkingDays = "COMPLETION_MINIMUM_WORKING_DAYS";

        /// <summary>
        /// Metadata type of check key used to retrieve report summary value when atomic check state is DONE_OK
        /// </summary>
        public const string kReportSummaryDoneOkKey = "REPORT_SUMMARY_VALUE_DONE_OK";

        /// <summary>
        /// Metadata type of check key used to retrieve report summary value when atomic check state is DONE_KO
        /// </summary>
        public const string kReportSummaryDoneKoKey = "REPORT_SUMMARY_VALUE_DONE_KO";

        /// <summary>
        ///  Metadata type of check key used to retrieve the first investigation place done during atomic check processing 
        /// (in office or on on field)
        /// </summary>
        public const string kFirstInvestigationPlaceKey = "FIRST_INVESTIGATION_PLACE";

        /// <summary>
        ///  Metadata type of check key used to retrieve the second investigation place done during atomic check processing 
        /// (in office or on on field)
        /// </summary>
        public const string kSecondInvestigationPlaceKey = "SECOND_INVESTIGATION_PLACE";

        /// <summary>
        ///  Metadata type of check key used to know if a type of check can be wronly qualified or not 
        /// (in office or on on field)
        /// </summary>
        public const string kCanBeWronlyQualifiedKey = "CAN_BE_WRONGLY_QUALIFIED";


        /// <summary>
        /// Metadata type of check ke used to check if the type of check has availibility value
        /// </summary>
        public const string kAvailabilityCriterion = "AVAILABILITY_CRITERION";


        /// <summary>
        /// Metadata type of check ke used to check if the type of check has workload value
        /// </summary>
        public const string kWorkLoadCriterion = "WORKLOAD_CRITERION";

        /// <summary>
        /// Metadata type of check ke used to check if the type of check has already assigned value
        /// </summary>
        public const string kAlreadyAssignedCriterion = "ALREADY_ASSIGNED_CRITERION";


        /// <summary>
        /// Metadata type of check ke used to check if the type of check has skill value
        /// </summary>
        public const string kSkillCriterion = "SKILL_CRITERION";


        /// <summary>
        /// Metadata type of check ke used to check if the type of check has geographical value
        /// </summary>
        public const string kGeographicalCriterion = "GEOGRAPHICAL_CRITERION";

        /// <summary>
        ///  Metadata type of check value used when to investigation place are applicable 
        /// (in office or on on field)
        /// </summary>
        public const string kInvestigationPlaceNotApplicableValue = "N/A";

        /// <summary>
        /// Value of type of check meta category
        /// </summary>
        public const string kOfficeCategory = "Office";


        /// <summary>
        /// Value of type of check meta category
        /// </summary>
        public const string kOnFieldCategory = "On field";

        /// <summary>
        /// Metadata type of check value used to know when a report summary is mandatory for an atomic check
        /// </summary>
        public const string kReportSummaryMandatoryValue = "Mandatory";


        /// <summary>
        /// Metadata type of check value Yes
        /// </summary>
        public const string kYesValue = "Yes";

        /// <summary>
        /// Metadata type of check value No
        /// </summary>
        public const string kNoValue = "No";

        #endregion

        #region IEntity interface method definition

        public void SetId(int id)
        {
            TypeOfCheckMetaId = id;
        }

        public int GetId()
        {
            return TypeOfCheckMetaId;
        }

        public void SetTenantId(byte id)
        {
            TypeOfCheckMetaTenantId = id;
        }

        public byte GetTenantId()
        {
            return TypeOfCheckMetaTenantId;
        }

        public void InitializeEntity()
        {

        }

        #endregion
    }
}
