//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;

    public partial class TypeOfCheckScreeningLevelVersion : IEntity
    {
        public void SetId(int id)
        {
            throw new NotImplementedException();
        }


        public int GetId()
        {
            return TypeOfCheckId;
        }

        public void SetTenantId(byte id)
        {
            TypeOfCheckScreeningTenantId = id;
        }

        public byte GetTenantId()
        {
            return TypeOfCheckScreeningTenantId;
        }

        public void InitializeEntity()
        {

        }

        /// <summary>
        /// Return true whether this type of check is an education type of check
        /// </summary>
        /// <returns></returns>
        public bool IsEducationTypeOfCheck()
        {
            return this.TypeOfCheck.IsEducationTypeOfCheck();
        }

        /// <summary>
        /// Return true whether this type of check is an employment type of check
        /// </summary>
        /// <returns></returns>
        public bool IsEmploymentTypeOfCheck()
        {
            return this.TypeOfCheck.IsEmploymentTypeOfCheck();
        }

        /// <summary>
        /// Return true whether this type of check is a neighborhood type of check
        /// </summary>
        /// <returns></returns>
        public bool IsNeighborhoodTypeOfCheck()
        {
            return this.TypeOfCheck.IsNeighborhoodTypeOfCheck();
        }

        /// <summary>
        /// Return true whether this type of check is a contact number type of check
        /// </summary>
        /// <returns></returns>
        public bool IsContactNumberTypeOfCheck()
        {
            return this.TypeOfCheck.IsContactNumberTypeOfCheck();
        }

    }
}
