//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webpages_Roles:IEntity
    {
        /// <summary>
        /// Role screener
        /// </summary>
        public const string kScreenerRole = "Screener";

        /// <summary>
        /// Role administrator
        /// </summary>
        public const string kAdministratorRole = "Administrator";

        /// <summary>
        /// Role Account manager
        /// </summary>
        public const string kAccountManagerRole = "Account manager";

        /// <summary>
        /// Role HR
        /// </summary>
        public const string kHrRole = "HR";

        /// <summary>
        /// Role Production manager
        /// </summary>
        public const string kProductionManagerRole = "Production manager";

        /// <summary>
        /// Role Quality control
        /// </summary>
        public const string kQualityControlRole = "Quality control";

        /// <summary>
        /// Role Qualifier
        /// </summary>
        public const string kQualifierRole = "Qualifier";

        /// <summary>
        /// Role Client
        /// </summary>
        public const string kClientRole = "Client";

        public void SetId(int id)
        {
            RoleId = id;
        }


        public int GetId()
        {
            return RoleId;
        }

        public void SetTenantId(byte id)
        {
            return;
        }

        public byte GetTenantId()
        {
            return 0;
        }

        public void InitializeEntity()
        {

        }
    }
}
