//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVScreeningWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVScreeningWeb.Resources.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic Check Ongoing.
        /// </summary>
        public static string AtomicCheckOnGoing {
            get {
                return ResourceManager.GetString("AtomicCheckOnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic Check Pending Validation.
        /// </summary>
        public static string AtomicCheckPendingValidation {
            get {
                return ResourceManager.GetString("AtomicCheckPendingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic Check To Dispatch.
        /// </summary>
        public static string AtomicCheckToDispatch {
            get {
                return ResourceManager.GetString("AtomicCheckToDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Completed.
        /// </summary>
        public static string ScreeningCompleted {
            get {
                return ResourceManager.GetString("ScreeningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Ongoing.
        /// </summary>
        public static string ScreeningOnGoing {
            get {
                return ResourceManager.GetString("ScreeningOnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening To Qualify.
        /// </summary>
        public static string ScreeningToQualify {
            get {
                return ResourceManager.GetString("ScreeningToQualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening To Submit.
        /// </summary>
        public static string ScreeningToSubmit {
            get {
                return ResourceManager.GetString("ScreeningToSubmit", resourceCulture);
            }
        }
    }
}
